# Generated by Django 4.1.6 on 2023-02-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0002_alter_camiones_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiones',
            name='imagen',
            field=models.ImageField(null=True, upload_to='camiones', verbose_name='Foto camion'),
        ),
    ]
