# Generated by Django 4.1.5 on 2023-01-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositos',
            name='fechaConseguido',
            field=models.DateField(null=True),
        ),
    ]
