# Generated by Django 4.1.6 on 2023-02-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0002_receta_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='recetario', verbose_name='Foto receta'),
        ),
    ]
